FROM php:7.4-fpm

#RUN apt-get update
#RUN apt-get install -y php-apcu php-intl php-mbstring php-xml php-mysql php-calendar

RUN apt-get update; \
    apt-get install -y --no-install-recommends libicu-dev libonig-dev librsvg2-bin imagemagick python3; \
    docker-php-ext-install calendar intl mbstring mysqli opcache; \
    pecl install APCu-5.1.21; \
    docker-php-ext-enable apcu; \
    rm -r /tmp/pear; \
    rm -rf /var/lib/apt/lists/*

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
    php composer-setup.php --install-dir=/usr/local/bin --filename=composer && \
    php -r "unlink('composer-setup.php');"